####**IMPORTANDO LIBRERIA NUMPY**

In [ ]:
import numpy as np # el np es un alias del nombre de la biblioteca numpy
import sys # este paquete maneja funciones de sistema

**CREANDO LISTA DE 10 ELEMENTOS**

In [ ]:
lista1 = list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Consulta el tipo de dato

In [ ]:
type(lista1)

list

**TRANSFORMANDO UNA LISTA A UN ARRAY**
Recordar que un 'array' es una estructura propia de la libreria numpy

In [ ]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Consultando el tipo de dato numerico del arreglo

In [ ]:
arreglo.dtype

dtype('int64')

#### Crear una lista de solo numeros unos

In [ ]:
unos = np.ones(10)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Creando una lista de solo numeros ceros

In [ ]:
ceros = np.zeros(10)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Transformando la lista mixta en array

In [ ]:
arreglo2 = np.array(lista2)
arreglo2

array(['Victor', '2', '5', '6', 'True'], dtype='<U21')

#### Lista de Datos Compuestos (Transformando a Array)

In [ ]:
lista2 = ['Victor', 2, 5, 6, True]
lista2

['Victor', 2, 5, 6, True]

#### Consultando la cantidad de memoria ocupada por estructura

In [ ]:
memoria_lista = sys.getsizeof(lista1)
memoria_arreglo = sys.getsizeof(arreglo)

print(f"Memoria ocupada por la lista: {memoria_lista} bytes")
print(f"Memoria ocupada por el array: {memoria_arreglo} bytes")

Memoria ocupada por la lista: 136 bytes
Memoria ocupada por el array: 192 bytes


#### **Otros métodos de Numpy**

In [ ]:
print("Shape:",         arreglo.shape)    #Dimensiones
print("Dimensiones:",   arreglo.ndim)     #Numero de ejes
print("Tamaño:",        arreglo.size)     #Total de elementos
print("Tipo dato:",     arreglo.dtype)    #Tipo almacenado
print("Bytes/elem:",    arreglo.itemsize) #Tamaño en bytes de cada elemento

Shape: (10,)
Dimensiones: 1
Tamaño: 10
Tipo dato: int64
Bytes/elem: 8


#### **Obteniendo el Promedio del Arreglo**

In [ ]:
promedio = np.mean(lista1)
promedio

np.float64(5.5)

#### **Transformando el arreglo de Int a Float**

El metodo astype() transforma los elementos del arreglo a un tipo determinado de dato numerico

In [ ]:
new_arreglo = arreglo.astype(np.float32)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [ ]:
new_arreglo.dtype

dtype('float32')

In [ ]:
mediana = np.median(lista1)
mediana

np.float64(5.5)

In [ ]:
promedio = np.mean(arreglo)
promedio

np.float64(5.5)

#### **Aplicando el Paquete Random**
Se genera una lista de numeros enteros aleatorios, que van desde 1 al 100

In [ ]:
np.random.rand() # genera numeros aleatorios del rango [0,1]

0.09869079301120975

In [ ]:
np.random.rand(5) # genera numeros aleatorios (n cantidad)

array([0.35077546, 0.83147016, 0.51912038, 0.67194656, 0.65617898])

In [ ]:
np.random.rand(10,4)

array([[0.84478399, 0.56513066, 0.60218098, 0.87661029],
       [0.52340773, 0.18828184, 0.60810737, 0.03374543],
       [0.78837611, 0.73480043, 0.60251742, 0.73708264],
       [0.97954833, 0.26670741, 0.79926652, 0.96564479],
       [0.85183299, 0.90781745, 0.58710611, 0.83315088],
       [0.33594284, 0.88505737, 0.46028452, 0.81521436],
       [0.42578611, 0.81900848, 0.22420324, 0.49780474],
       [0.86839109, 0.23680766, 0.49233275, 0.41575582],
       [0.0465299 , 0.75579478, 0.43071678, 0.01758533],
       [0.56491668, 0.57599864, 0.73634652, 0.27346649]])

In [ ]:
np.random.randint(1, 100, 10) # generando 10 numeros eneteros aleatorios del 1 al 100

array([25, 10, 89, 60, 87, 71, 82, 13,  7, 57])

#### **Metodo Arange**

In [ ]:
arreglo_3 = np.arange(1,11)
arreglo_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])